name: Test
on: [push]

jobs:
  build:
    name: Run tests with Gradle
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Set up JDK 12
      uses: actions/setup-java@v1
      with:
        java-version: 12 
    - name: Test
      run: ./gradlew --no-daemon test
